### ISSUE TITLE
Issue with coleman_policy_iter lecture

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#501]
`coverage` on the build server is indicating an issue in `coleman_policy_iter` lecture. It looks like a possible issue with `numba` compatibility. Will need to investigate further.

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-9-7c0cb6c2538d> in <module>
      7 for i in range(sim_length):
      8     σ = K(σ)  # Time iteration
----> 9     v = T(v)  # Value function iteration
     10 
     11 # Calculate difference with actual solution

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    348                 e.patch_message(msg)
    349 
--> 350             error_rewrite(e, 'typing')
    351         except errors.UnsupportedError as e:
    352             # Something unsupported is present in the user code, add help info

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    315                 raise e
    316             else:
--> 317                 reraise(type(e), e, None)
    318 
    319         argtypes = []

~/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7f39601f9d68>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/errors.py", line 627, in new_error_context
    yield
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 400, in lower_inst
    self.lower_static_raise(inst)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 442, in lower_static_raise
    self.return_exception(inst.exc_class, inst.exc_args, loc=self.loc)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 163, in return_exception
    func_name=self.func_ir.func_id.func_name)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/targets/callconv.py", line 365, in return_user_exc
    fname = loc._raw_function_name()
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/ir.py", line 63, in _raw_function_name
    return self._defmatcher.match(defn.strip()).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 144, in propagate
    constraint(typeinfer)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 428, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 447, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 1252, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/typing/context.py", line 191, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/typing/context.py", line 243, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/types/functions.py", line 271, in get_call_type
    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 274, in get_call_template
    self.compile(tuple(args))
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 658, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 731, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 681, in _backend
    lowered = lowerfn()
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 668, in backend_nopython_mode
    self.metadata)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 1063, in native_lowering_stage
    lower.lower()
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/qebuild/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/errors.py", line 635, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/qebuild/anaconda3/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
'NoneType' object has no attribute 'groups'

File "../../../../../../../../anaconda3/lib/python3.7/site-packages/quantecon/optimize/scalar_maximization.py", line 50:
    ... def f(x):
        <source elided>
    if not np.isfinite(a):
        raise ValueError("a must be finite.")
        ^

[1] During: lowering "raise <class 'ValueError'>('a must be finite.')" at /home/qebuild/anaconda3/lib/python3.7/site-packages/quantecon/optimize/scalar_maximization.py (50)
[2] During: resolving callee type: type(CPUDispatcher(<function brent_max at 0x7f3961cbb488>))
[3] During: typing of call at <ipython-input-5-3f7c7f7b0dfc> (30)

--%<----------------------------------------------------------------------------


File "<ipython-input-5-3f7c7f7b0dfc>", line 30:
    def T(v):
        <source elided>
            # Solve for optimal v at y
            v_max = brent_max(objective, 1e-10, y, args=(v, y))[1]
            ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by mmcky** [comment]
this is no longer an issue on the latest `build`. Closing.
