### ISSUE TITLE
BUG: Lecture `sci_libs` lecture with `numba=0.44.1`

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#515]
`numba` strikes again! With `numba=0.44.1` the `sci_libs` library is failing for `compute_series` example in `Exercise 1`:

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/8263752/61512107-42fac080-aa3c-11e9-8df0-7e49d92cff2d.png">

```
<ipython-input-16-333f8de3ec8c>:1: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "compute_series" failed type inference due to: Invalid use of Function(<built-in function empty>) with argument(s) of type(s): (int64, dtype=Function(<class 'int'>))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function empty>)
[2] During: typing of call at <ipython-input-16-333f8de3ec8c> (2)


File "<ipython-input-16-333f8de3ec8c>", line 2:
def compute_series(n):
    x = np.empty(n, dtype=int)
    ^

  def compute_series(n):
<ipython-input-16-333f8de3ec8c>:1: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "compute_series" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "<ipython-input-16-333f8de3ec8c>", line 5:
def compute_series(n):
    <source elided>
    U = np.random.uniform(0, 1, size=n)
    for t in range(1, n):
    ^

  def compute_series(n):
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    660     try:
--> 661         yield
    662     except NumbaError as e:

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower_block(self, block)
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 

~/anaconda3/lib/python3.7/site-packages/numba/pylowering.py in lower_inst(self, inst)
    175         else:
--> 176             raise NotImplementedError(type(inst), inst)
    177 

NotImplementedError: (<class 'numba.ir.StaticSetItem'>, x[0] = $const0.7)

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-20-7591f0c5af7d> in <module>
----> 1 x = compute_series_numba(n)
      2 print(np.mean(x == 0))

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    368                     e.patch_message(''.join(e.args) + help_msg)
    369             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 370             raise e
    371 
    372     def inspect_llvm(self, signature=None):

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    325                 argtypes.append(self.typeof_pyval(a))
    326         try:
--> 327             return self.compile(tuple(argtypes))
    328         except errors.TypingError as e:
    329             # Intercept typing error that may be due to an argument

~/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in compile(self, sig)
    657 
    658             self._cache_misses[sig] += 1
--> 659             cres = self._compiler.compile(args, return_type)
    660             self.add_overload(cres)
    661             self._cache.save_overload(sig, cres)

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     81                                       args=args, return_type=return_type,
     82                                       flags=flags, locals=self.locals,
---> 83                                       pipeline_class=self.pipeline_class)
     84         # Check typing error if object mode is used
     85         if cres.typing_error is not None and not flags.enable_pyobject:

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    953     pipeline = pipeline_class(typingctx, targetctx, library,
    954                               args, return_type, flags, locals)
--> 955     return pipeline.compile_extra(func)
    956 
    957 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_extra(self, func)
    375         self.lifted = ()
    376         self.lifted_from = None
--> 377         return self._compile_bytecode()
    378 
    379     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_bytecode(self)
    884         """
    885         assert self.func_ir is None
--> 886         return self._compile_core()
    887 
    888     def _compile_ir(self):

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_core(self)
    871         self.define_pipelines(pm)
    872         pm.finalize()
--> 873         res = pm.run(self.status)
    874         if res is not None:
    875             # Early pipeline completion

~/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    252                     # No more fallback pipelines?
    253                     if is_final_pipeline:
--> 254                         raise patched_exception
    255                     # Go to next fallback pipeline
    256                     else:

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    243                 try:
    244                     event("-- %s" % stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in stage_objectmode_frontend(self)
    461         if self.flags.enable_looplift:
    462             assert not self.lifted
--> 463             cres = self.frontend_looplift()
    464             if cres is not None:
    465                 raise _EarlyPipelineCompletion(cres)

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in frontend_looplift(self)
    433                               self.args, self.return_type,
    434                               outer_flags, self.locals,
--> 435                               lifted=tuple(loops), lifted_from=None)
    436             return cres
    437 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_ir(typingctx, targetctx, func_ir, args, return_type, flags, locals, lifted, lifted_from, is_lifted_loop, library, pipeline_class)
   1015                                   args, return_type, flags, locals)
   1016         return pipeline.compile_ir(func_ir=func_ir, lifted=lifted,
-> 1017                                 lifted_from=lifted_from)
   1018 
   1019 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in compile_ir(self, func_ir, lifted, lifted_from)
    383 
    384         self._set_and_check_ir(func_ir)
--> 385         return self._compile_ir()
    386 
    387     def stage_analyze_bytecode(self):

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_ir(self)
    891         """
    892         assert self.func_ir is not None
--> 893         return self._compile_core()
    894 
    895 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _compile_core(self)
    871         self.define_pipelines(pm)
    872         pm.finalize()
--> 873         res = pm.run(self.status)
    874         if res is not None:
    875             # Early pipeline completion

~/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    252                     # No more fallback pipelines?
    253                     if is_final_pipeline:
--> 254                         raise patched_exception
    255                     # Go to next fallback pipeline
    256                     else:

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    243                 try:
    244                     event("-- %s" % stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in stage_objectmode_backend(self)
    709         """
    710         lowerfn = self.backend_object_mode
--> 711         self._backend(lowerfn, objectmode=True)
    712 
    713         # Warn, deprecated behaviour, code compiled in objmode without

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    685             self.library.enable_object_caching()
    686 
--> 687         lowered = lowerfn()
    688         signature = typing.signature(self.return_type, *self.args)
    689         self.cr = compile_result(

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in backend_object_mode(self)
    657                                      self.library,
    658                                      self.func_ir,
--> 659                                      self.flags)
    660 
    661     def backend_nopython_mode(self):

~/anaconda3/lib/python3.7/site-packages/numba/compiler.py in py_lowering_stage(targetctx, library, interp, flags)
   1146     with targetctx.push_code_library(library):
   1147         lower = pylowering.PyLower(targetctx, library, fndesc, interp)
-> 1148         lower.lower()
   1149         if not flags.no_cpython_wrapper:
   1150             lower.create_cpython_wrapper()

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower(self)
    175         if self.generator_info is None:
    176             self.genlower = None
--> 177             self.lower_normal_function(self.fndesc)
    178         else:
    179             self.genlower = self.GeneratorLower(self)

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    216         # Init argument values
    217         self.extract_function_arguments()
--> 218         entry_block_tail = self.lower_function_body()
    219 
    220         # Close tail of entry block

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower_function_body(self)
    241             bb = self.blkmap[offset]
    242             self.builder.position_at_end(bb)
--> 243             self.lower_block(block)
    244 
    245         self.post_lower()

~/anaconda3/lib/python3.7/site-packages/numba/lowering.py in lower_block(self, block)
    256             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 
    260     def create_cpython_wrapper(self, release_gil=False):

~/anaconda3/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/anaconda3/lib/python3.7/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    667         from numba import config
    668         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 669         six.reraise(type(newerr), newerr, tb)
    670 
    671 

~/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
(<class 'numba.ir.StaticSetItem'>, x[0] = $const0.7)

File "<ipython-input-16-333f8de3ec8c>", line 3:
def compute_series(n):
    <source elided>
    x = np.empty(n, dtype=int)
    x[0] = 1  # Start in state 1
    ^

[1] During: lowering "x[0] = $const0.7" at <ipython-input-16-333f8de3ec8c> (3)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by jstac** [comment]
Hmmm, this is a weird one.  I get the same error after `conda install numba=0.44`.  

I also get an error when I try to execute any block with `%%cython` cell magic.  The error message is `
LinkError: command 'gcc' failed with exit status 1`.

I have `gcc` installed.  @AnjuJoon or @shizejin, might either of you have time to try to get to the bottom of these problems and make recommendations?

Also, I suggest we replace the four lines after "Important Note:" with a brief discussion of the dependencies of cython for Windows, Linux and Mac.

**Comment by shizejin** [comment]
Hi @mmcky @jstac, I got the same error and I could solve it by replacing `int` with `np.int32` or `np.int64`. I agree that this is weird since `int` should be supported by `jitclass`. I am not sure if they stop supporting it or this is a bug.

@jstac The `%%cython` cell magic seems to be working on my machine.

I will look into these more tomorrow.

**Comment by jstac** [comment]
Thanks @shizejin. 

Regarding Numba, I see that 0.45 is out: http://numba.pydata.org/numba-doc/latest/release-notes.html

 It might be worth testing with 0.45 and then [posting an issue](https://github.com/numba/numba/issues) about this problem with a minimal example if it our code still fails.  

(Even if the bug is intentional, this seems like poor behavior.  It would be better if Numba defaulted to `np.int64` rather than failed.  You could suggest that if you post an issue -- and if you agree with me.)

**Comment by shizejin** [comment]
Hi @jstac, I found discussion about the problem we are having here numba/numba#4315. It is a requested feature (I don't know how did it work for versions before 0.44.0...), and currently the most natural way to solve this is to replace `np.int` with `np.int_`, which I have tested that actually works for our example.
